version: 2

project_name: awsdeny

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: awsdeny
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/leredteam/awsdeny/cmd.version={{.Version}}
      - -X github.com/leredteam/awsdeny/license.publicKeyB64={{ .Env.LICENSE_PUBLIC_KEY }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: leredteam
    name: awsdeny
