package output

import (
	"bytes"
	"strings"
	"testing"

	"github.com/leredteam/awsdeny/internal"
)

func TestGitHubComment_ContainsMarkdown(t *testing.T) {
	result := internal.AnalysisResult{
		Parsed: internal.ParsedError{
			Action:    "s3:GetObject",
			Resource:  "arn:aws:s3:::bucket/key",
			Principal: "arn:aws:iam::123:role/MyRole",
		},
		Explanation: internal.Explanation{
			Summary:     "Blocked by SCP",
			DenyType:    "explicit",
			SourceType:  "scp",
			SourceARN:   "arn:aws:organizations::111:policy/p-abc",
			Reason:      "SCP denies this action",
			Confidence:  "high",
			Level:       1,
			HeuristicID: "SCP-001",
			Suggestions: []internal.Suggestion{
				{Action: "Contact admin", Difficulty: "medium"},
			},
		},
	}

	var buf bytes.Buffer
	GitHubComment(&buf, result)
	out := buf.String()

	expectations := []string{
		"## AWS AccessDenied Explanation",
		"**Action:** `s3:GetObject`",
		"**Resource:** `arn:aws:s3:::bucket/key`",
		"### Analysis",
		"| **Type** | Explicit deny |",
		"### Reason",
		"### Suggested Fixes",
		"1. Contact admin",
		"*Generated by [awsdeny]",
	}

	for _, exp := range expectations {
		if !strings.Contains(out, exp) {
			t.Errorf("output missing expected string: %q", exp)
		}
	}
}

func TestGitHubComment_WithWarnings(t *testing.T) {
	result := internal.AnalysisResult{
		Parsed: internal.ParsedError{},
		Explanation: internal.Explanation{
			Confidence: "low",
			DenyType:   "unknown",
			SourceType: "unknown",
			Warnings:   []string{"Enrichment failed"},
		},
	}

	var buf bytes.Buffer
	GitHubComment(&buf, result)
	out := buf.String()

	if !strings.Contains(out, "### Warnings") {
		t.Error("output missing warnings section")
	}
	if !strings.Contains(out, "Enrichment failed") {
		t.Error("output missing warning text")
	}
}
