package output

import (
	"fmt"
	"io"
	"unicode"

	"github.com/leredteam/awsdeny/internal"
)

func capitalizeGH(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// GitHubComment writes a PR comment formatted in markdown.
func GitHubComment(w io.Writer, result internal.AnalysisResult) {
	p := result.Parsed
	e := result.Explanation

	fmt.Fprintln(w, "## AWS AccessDenied Explanation")
	fmt.Fprintln(w)

	if p.Action != "" {
		fmt.Fprintf(w, "**Action:** `%s`\n", p.Action)
	}
	if p.Resource != "" {
		fmt.Fprintf(w, "**Resource:** `%s`\n", p.Resource)
	}
	if p.Principal != "" {
		fmt.Fprintf(w, "**Principal:** `%s`\n", p.Principal)
	}
	fmt.Fprintln(w)

	fmt.Fprintln(w, "### Analysis")
	fmt.Fprintln(w, "| | |")
	fmt.Fprintln(w, "|---|---|")

	if e.DenyType != "" && e.DenyType != "unknown" {
		fmt.Fprintf(w, "| **Type** | %s deny |\n", capitalizeGH(e.DenyType))
	}
	if e.SourceType != "" && e.SourceType != "unknown" {
		source := sourceTypeLabel(e.SourceType)
		if e.SourceARN != "" {
			source += fmt.Sprintf(" (`%s`)", e.SourceARN)
		}
		fmt.Fprintf(w, "| **Source** | %s |\n", source)
	}
	fmt.Fprintf(w, "| **Confidence** | %s", capitalizeGH(e.Confidence))
	if e.ConfidenceReason != "" {
		fmt.Fprintf(w, " (%s)", e.ConfidenceReason)
	}
	fmt.Fprintln(w, " |")
	fmt.Fprintln(w)

	if e.Reason != "" {
		fmt.Fprintln(w, "### Reason")
		fmt.Fprintln(w, e.Reason)
		fmt.Fprintln(w)
	}

	if len(e.Suggestions) > 0 {
		fmt.Fprintln(w, "### Suggested Fixes")
		for i, s := range e.Suggestions {
			fmt.Fprintf(w, "%d. %s\n", i+1, s.Action)
		}
		fmt.Fprintln(w)
	}

	if len(e.Warnings) > 0 {
		fmt.Fprintln(w, "### Warnings")
		for _, warn := range e.Warnings {
			fmt.Fprintf(w, "- %s\n", warn)
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "*Generated by [awsdeny](https://github.com/leredteam/awsdeny)*")
}

// GitHubJobSummary writes output suitable for $GITHUB_STEP_SUMMARY.
func GitHubJobSummary(w io.Writer, result internal.AnalysisResult) {
	// Same format as PR comment
	GitHubComment(w, result)
}
